services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    command: "poetry run python main.py"
    build: ./mirror-test-app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"